// Dados de exemplo para o modo demo (VITE_DEMO_MODE=true).
// Tudo em memória — nada disso toca uma rede ou banco de verdade.

// Começa bem acima de qualquer número usado nos IDs fixos do seed abaixo
// (ex: 'os-1', 'item-3'), para nunca colidir com um registro novo criado
// durante a sessão.
let contador = 100000
export function gerarId(prefixo = 'id') {
  contador += 1
  return `${prefixo}-${contador}`
}

function isoAtras(dias, horas = 12) {
  const d = new Date()
  d.setDate(d.getDate() - dias)
  d.setHours(horas, 0, 0, 0)
  return d.toISOString()
}

function dataAtras(dias) {
  const d = new Date()
  d.setDate(d.getDate() - dias)
  return d.toISOString().slice(0, 10)
}

function dataNoFuturo(dias) {
  const d = new Date()
  d.setDate(d.getDate() + dias)
  return d.toISOString().slice(0, 10)
}

export const AGORA = new Date().toISOString()

export const usuarioAdmin = { id: 'user-admin', email: 'admin@oticamontesinai.com' }
export const usuarioVendedor = { id: 'user-vend-1', email: 'carlos@oticamontesinai.com' }
export const usuarioFinanceiro = { id: 'user-fin-1', email: 'beatriz@oticamontesinai.com' }
export const usuarioCliente = { id: 'user-cli-1', email: '60582664918@clientes.oticamontesinai.internal' }

export const db = {
  funcionarios: [
    {
      id: 'func-admin',
      user_id: usuarioAdmin.id,
      nome: 'Ana Souza',
      email: usuarioAdmin.email,
      perfil: 'admin',
      ativo: true,
      telefone: '(11) 99999-0001',
      data_admissao: '2022-01-10',
      created_at: isoAtras(700),
    },
    {
      id: 'func-vend-1',
      user_id: usuarioVendedor.id,
      nome: 'Carlos Lima',
      email: usuarioVendedor.email,
      perfil: 'vendedor',
      ativo: true,
      telefone: '(11) 99999-0002',
      data_admissao: '2023-03-15',
      created_at: isoAtras(500),
    },
    {
      id: 'func-fin-1',
      user_id: usuarioFinanceiro.id,
      nome: 'Beatriz Santos',
      email: usuarioFinanceiro.email,
      perfil: 'financeiro',
      ativo: true,
      telefone: '(11) 99999-0003',
      data_admissao: '2023-06-01',
      created_at: isoAtras(400),
    },
    {
      id: 'func-vend-2',
      user_id: 'user-vend-2',
      nome: 'Rafael Torres',
      email: 'rafael@oticamontesinai.com',
      perfil: 'vendedor',
      ativo: false,
      telefone: '(11) 99999-0004',
      data_admissao: '2022-08-20',
      created_at: isoAtras(600),
    },
  ],

  clientes: [
    {
      id: 'cli-1',
      user_id: usuarioCliente.id,
      nome: 'Maria Silva',
      cpf: '60582664918',
      telefone: '(11) 98888-1001',
      email: 'maria.silva@example.com',
      cep: '01310-930',
      endereco: 'Avenida Paulista',
      numero: '1000',
      complemento: 'Apto 52',
      bairro: 'Bela Vista',
      cidade: 'São Paulo',
      uf: 'SP',
      data_nascimento: '1985-04-12',
      foto_url: null,
      observacoes: 'Prefere armações leves, sensibilidade a luz.',
      ativo: true,
      created_at: isoAtras(420),
    },
    {
      id: 'cli-2',
      user_id: null,
      nome: 'João Pereira',
      cpf: '89039135665',
      telefone: '(11) 98888-1002',
      email: 'joao.pereira@example.com',
      cep: '04538-133',
      endereco: 'Avenida Brigadeiro Faria Lima',
      numero: '2232',
      complemento: '',
      bairro: 'Itaim Bibi',
      cidade: 'São Paulo',
      uf: 'SP',
      data_nascimento: '1978-11-02',
      foto_url: null,
      observacoes: '',
      ativo: true,
      created_at: isoAtras(380),
    },
    {
      id: 'cli-3',
      user_id: null,
      nome: 'Fernanda Costa',
      cpf: '17685505223',
      telefone: '(11) 98888-1003',
      email: 'fernanda.costa@example.com',
      cep: '05407-002',
      endereco: 'Rua Harmonia',
      numero: '312',
      complemento: '',
      bairro: 'Sumarezinho',
      cidade: 'São Paulo',
      uf: 'SP',
      data_nascimento: '1992-02-20',
      foto_url: null,
      observacoes: 'Cliente antiga, indicou 3 novos clientes.',
      ativo: true,
      created_at: isoAtras(300),
    },
    {
      id: 'cli-4',
      user_id: null,
      nome: 'Pedro Almeida',
      cpf: '46241075861',
      telefone: '(11) 98888-1004',
      email: 'pedro.almeida@example.com',
      cep: '',
      endereco: '',
      numero: '',
      complemento: '',
      bairro: '',
      cidade: '',
      uf: '',
      data_nascimento: null,
      foto_url: null,
      observacoes: '',
      ativo: true,
      created_at: isoAtras(200),
    },
    {
      id: 'cli-5',
      user_id: null,
      nome: 'Luciana Ferreira',
      cpf: '74797446412',
      telefone: '(11) 98888-1005',
      email: 'luciana.ferreira@example.com',
      cep: '',
      endereco: '',
      numero: '',
      complemento: '',
      bairro: '',
      cidade: '',
      uf: '',
      data_nascimento: '1990-07-30',
      foto_url: null,
      observacoes: 'Inativa há mais de 6 meses.',
      ativo: true,
      created_at: isoAtras(500),
    },
    {
      id: 'cli-6',
      user_id: null,
      nome: 'Roberto Nunes',
      cpf: '03344916149',
      telefone: '(11) 98888-1006',
      email: 'roberto.nunes@example.com',
      cep: '',
      endereco: '',
      numero: '',
      complemento: '',
      bairro: '',
      cidade: '',
      uf: '',
      data_nascimento: '1975-09-05',
      foto_url: null,
      observacoes: 'Cliente desativado a pedido.',
      ativo: false,
      created_at: isoAtras(650),
    },
  ],

  receitas: [
    {
      id: 'rec-1',
      cliente_id: 'cli-1',
      esferico_od: -1.0,
      cilindrico_od: -0.5,
      eixo_od: 90,
      esferico_oe: -1.25,
      cilindrico_oe: -0.5,
      eixo_oe: 85,
      adicao: null,
      dnp: 31,
      altura: 18,
      tipo_lente: 'visao_simples',
      medico: 'Dr. Ricardo Mendes',
      data_consulta: dataAtras(400),
      foto_url: null,
      ativa: false,
      criado_por: 'func-vend-1',
      created_at: isoAtras(400),
    },
    {
      id: 'rec-2',
      cliente_id: 'cli-1',
      esferico_od: -1.5,
      cilindrico_od: -0.75,
      eixo_od: 90,
      esferico_oe: -1.75,
      cilindrico_oe: -0.5,
      eixo_oe: 80,
      adicao: null,
      dnp: 31,
      altura: 18,
      tipo_lente: 'visao_simples',
      medico: 'Dr. Ricardo Mendes',
      data_consulta: dataAtras(30),
      foto_url: null,
      ativa: true,
      criado_por: 'func-vend-1',
      created_at: isoAtras(30),
    },
    {
      id: 'rec-3',
      cliente_id: 'cli-2',
      esferico_od: -2.0,
      cilindrico_od: 0,
      eixo_od: 0,
      esferico_oe: -2.25,
      cilindrico_oe: 0,
      eixo_oe: 0,
      adicao: 1.5,
      dnp: 32,
      altura: 20,
      tipo_lente: 'multifocal',
      medico: 'Dra. Camila Rocha',
      data_consulta: dataAtras(90),
      foto_url: null,
      ativa: true,
      criado_por: 'func-vend-1',
      created_at: isoAtras(90),
    },
    {
      id: 'rec-4',
      cliente_id: 'cli-3',
      esferico_od: 0.5,
      cilindrico_od: -0.25,
      eixo_od: 45,
      esferico_oe: 0.75,
      cilindrico_oe: -0.25,
      eixo_oe: 50,
      adicao: null,
      dnp: 30,
      altura: 17,
      tipo_lente: 'visao_simples',
      medico: 'Dr. Ricardo Mendes',
      data_consulta: dataAtras(60),
      foto_url: null,
      ativa: true,
      criado_por: 'func-admin',
      created_at: isoAtras(60),
    },
  ],

  fornecedores: [
    {
      id: 'forn-1',
      nome: 'Ótica Lentes Premium Ltda',
      cnpj: '12.345.678/0001-90',
      telefone: '(11) 3333-1000',
      email: 'contato@lentespremium.com.br',
      endereco: 'Rua Industrial, 500 - São Paulo/SP',
      tipo: 'lente',
      contato: 'Sandra Oliveira',
      prazo_medio_dias: 7,
      created_at: isoAtras(600),
    },
    {
      id: 'forn-2',
      nome: 'Armações & Cia Distribuidora',
      cnpj: '98.765.432/0001-10',
      telefone: '(11) 3333-2000',
      email: 'vendas@armacoesecia.com.br',
      endereco: 'Av. dos Distribuidores, 200 - São Paulo/SP',
      tipo: 'armacao',
      contato: 'Marcos Vieira',
      prazo_medio_dias: 5,
      created_at: isoAtras(600),
    },
  ],

  produtos: [
    {
      id: 'prod-1',
      tipo: 'armacao',
      sku: 'ARM-001',
      marca: 'RayVision',
      modelo: 'Classic Redonda',
      cor: 'Preto Fosco',
      material: 'Acetato',
      custo: 80,
      preco: 220,
      estoque_atual: 12,
      estoque_minimo: 3,
      fornecedor_id: 'forn-2',
      prazo_dias: null,
      foto_url: null,
      ativo: true,
      created_at: isoAtras(500),
    },
    {
      id: 'prod-2',
      tipo: 'armacao',
      sku: 'ARM-002',
      marca: 'Urban Style',
      modelo: 'Quadrada Slim',
      cor: 'Azul Marinho',
      material: 'Metal',
      custo: 95,
      preco: 260,
      estoque_atual: 2,
      estoque_minimo: 3,
      fornecedor_id: 'forn-2',
      prazo_dias: null,
      foto_url: null,
      ativo: true,
      created_at: isoAtras(480),
    },
    {
      id: 'prod-3',
      tipo: 'armacao',
      sku: 'ARM-003',
      marca: 'RayVision',
      modelo: 'Aviador Clássico',
      cor: 'Dourado',
      material: 'Metal',
      custo: 110,
      preco: 320,
      estoque_atual: 6,
      estoque_minimo: 2,
      fornecedor_id: 'forn-2',
      prazo_dias: null,
      foto_url: null,
      ativo: true,
      created_at: isoAtras(450),
    },
    {
      id: 'prod-4',
      tipo: 'armacao',
      sku: 'ARM-004',
      marca: 'Kids Line',
      modelo: 'Infantil Flex',
      cor: 'Vermelho',
      material: 'TR90',
      custo: 60,
      preco: 150,
      estoque_atual: 8,
      estoque_minimo: 3,
      fornecedor_id: 'forn-2',
      prazo_dias: null,
      foto_url: null,
      ativo: true,
      created_at: isoAtras(400),
    },
    {
      id: 'prod-5',
      tipo: 'lente',
      sku: 'LEN-001',
      marca: 'ClearView',
      modelo: 'CR-39 Visão Simples',
      cor: null,
      material: 'Orgânico',
      custo: 90,
      preco: 250,
      estoque_atual: null,
      estoque_minimo: null,
      fornecedor_id: 'forn-1',
      prazo_dias: 7,
      foto_url: null,
      ativo: true,
      created_at: isoAtras(500),
    },
    {
      id: 'prod-6',
      tipo: 'lente',
      sku: 'LEN-002',
      marca: 'ClearView',
      modelo: 'CR-39 com Antirreflexo',
      cor: null,
      material: 'Orgânico',
      custo: 130,
      preco: 380,
      estoque_atual: null,
      estoque_minimo: null,
      fornecedor_id: 'forn-1',
      prazo_dias: 7,
      foto_url: null,
      ativo: true,
      created_at: isoAtras(500),
    },
    {
      id: 'prod-7',
      tipo: 'lente',
      sku: 'LEN-003',
      marca: 'MultiFocal Pro',
      modelo: 'Multifocal Digital',
      cor: null,
      material: 'Policarbonato',
      custo: 280,
      preco: 750,
      estoque_atual: null,
      estoque_minimo: null,
      fornecedor_id: 'forn-1',
      prazo_dias: 12,
      foto_url: null,
      ativo: true,
      created_at: isoAtras(500),
    },
    {
      id: 'prod-8',
      tipo: 'acessorio',
      sku: 'ACE-001',
      marca: 'CleanKit',
      modelo: 'Kit Limpeza + Estojo',
      cor: null,
      material: null,
      custo: 15,
      preco: 45,
      estoque_atual: 30,
      estoque_minimo: 5,
      fornecedor_id: 'forn-2',
      prazo_dias: null,
      foto_url: null,
      ativo: true,
      created_at: isoAtras(400),
    },
  ],

  ordens_servico: [
    {
      id: 'os-1',
      numero: 1001,
      cliente_id: 'cli-2',
      receita_id: 'rec-3',
      vendedor_id: 'func-vend-1',
      status: 'entregue',
      valor_total: 630,
      desconto: 30,
      motivo_desconto: null,
      forma_pagamento: 'pix',
      prazo_entrega: dataAtras(70),
      motivo_cancelamento: null,
      created_at: isoAtras(85),
      updated_at: isoAtras(70),
    },
    {
      id: 'os-2',
      numero: 1002,
      cliente_id: 'cli-1',
      receita_id: 'rec-2',
      vendedor_id: 'func-vend-1',
      status: 'pronto',
      valor_total: 600,
      desconto: 0,
      motivo_desconto: null,
      forma_pagamento: 'cartao_credito',
      prazo_entrega: dataAtras(2),
      motivo_cancelamento: null,
      created_at: isoAtras(20),
      updated_at: isoAtras(3),
    },
    {
      id: 'os-3',
      numero: 1003,
      cliente_id: 'cli-3',
      receita_id: 'rec-4',
      vendedor_id: 'func-vend-1',
      status: 'em_producao',
      valor_total: 570,
      desconto: 20,
      motivo_desconto: 'Cliente indicou outros clientes',
      forma_pagamento: 'boleto',
      prazo_entrega: dataNoFuturo(3),
      motivo_cancelamento: null,
      created_at: isoAtras(10),
      updated_at: isoAtras(8),
    },
    {
      id: 'os-4',
      numero: 1004,
      cliente_id: 'cli-4',
      receita_id: null,
      vendedor_id: 'func-vend-1',
      status: 'orcamento',
      valor_total: 220,
      desconto: 0,
      motivo_desconto: null,
      forma_pagamento: 'pix',
      prazo_entrega: null,
      motivo_cancelamento: null,
      created_at: isoAtras(1),
      updated_at: isoAtras(1),
    },
    {
      id: 'os-5',
      numero: 1005,
      cliente_id: 'cli-5',
      receita_id: null,
      vendedor_id: 'func-vend-2',
      status: 'cancelado',
      valor_total: 260,
      desconto: 0,
      motivo_desconto: null,
      forma_pagamento: 'dinheiro',
      prazo_entrega: null,
      motivo_cancelamento: 'Cliente desistiu da compra',
      created_at: isoAtras(45),
      updated_at: isoAtras(40),
    },
  ],

  os_itens: [
    { id: 'item-1', os_id: 'os-1', produto_id: 'prod-1', quantidade: 1, valor_unitario: 220 },
    { id: 'item-2', os_id: 'os-1', produto_id: 'prod-6', quantidade: 1, valor_unitario: 380 },
    { id: 'item-3', os_id: 'os-1', produto_id: 'prod-8', quantidade: 1, valor_unitario: 45 },
    { id: 'item-4', os_id: 'os-2', produto_id: 'prod-3', quantidade: 1, valor_unitario: 320 },
    { id: 'item-5', os_id: 'os-2', produto_id: 'prod-5', quantidade: 1, valor_unitario: 250 },
    { id: 'item-6', os_id: 'os-3', produto_id: 'prod-4', quantidade: 1, valor_unitario: 150 },
    { id: 'item-7', os_id: 'os-3', produto_id: 'prod-7', quantidade: 1, valor_unitario: 420 },
    { id: 'item-8', os_id: 'os-4', produto_id: 'prod-1', quantidade: 1, valor_unitario: 220 },
    { id: 'item-9', os_id: 'os-5', produto_id: 'prod-2', quantidade: 1, valor_unitario: 260 },
  ],

  os_status_historico: [
    { id: 'hist-1', os_id: 'os-1', status_anterior: null, status_novo: 'aprovado', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(85) },
    { id: 'hist-2', os_id: 'os-1', status_anterior: 'aprovado', status_novo: 'em_producao', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(80) },
    { id: 'hist-3', os_id: 'os-1', status_anterior: 'em_producao', status_novo: 'pronto', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(75) },
    { id: 'hist-4', os_id: 'os-1', status_anterior: 'pronto', status_novo: 'entregue', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(70) },
    { id: 'hist-5', os_id: 'os-2', status_anterior: null, status_novo: 'aprovado', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(20) },
    { id: 'hist-6', os_id: 'os-2', status_anterior: 'aprovado', status_novo: 'em_producao', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(15) },
    { id: 'hist-7', os_id: 'os-2', status_anterior: 'em_producao', status_novo: 'pronto', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(3) },
    { id: 'hist-8', os_id: 'os-3', status_anterior: null, status_novo: 'aprovado', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(10) },
    { id: 'hist-9', os_id: 'os-3', status_anterior: 'aprovado', status_novo: 'em_producao', funcionario_id: 'func-vend-1', motivo: null, created_at: isoAtras(8) },
    { id: 'hist-10', os_id: 'os-5', status_anterior: null, status_novo: 'aprovado', funcionario_id: 'func-vend-2', motivo: null, created_at: isoAtras(45) },
    { id: 'hist-11', os_id: 'os-5', status_anterior: 'aprovado', status_novo: 'cancelado', funcionario_id: 'func-vend-2', motivo: 'Cliente desistiu da compra', created_at: isoAtras(40) },
  ],

  pedidos_lente: [
    {
      id: 'pl-1',
      os_id: 'os-1',
      produto_id: 'prod-6',
      fornecedor_id: 'forn-1',
      status: 'recebido',
      prazo_estimado: dataAtras(78),
      data_recebimento: dataAtras(76),
      created_at: isoAtras(85),
    },
    {
      id: 'pl-2',
      os_id: 'os-2',
      produto_id: 'prod-5',
      fornecedor_id: 'forn-1',
      status: 'recebido',
      prazo_estimado: dataAtras(13),
      data_recebimento: dataAtras(4),
      created_at: isoAtras(20),
    },
    {
      id: 'pl-3',
      os_id: 'os-3',
      produto_id: 'prod-7',
      fornecedor_id: 'forn-1',
      status: 'em_producao',
      prazo_estimado: dataNoFuturo(2),
      data_recebimento: null,
      created_at: isoAtras(10),
    },
  ],

  pagamentos: [
    {
      id: 'pag-1',
      os_id: 'os-1',
      asaas_payment_id: 'demo_pay_1',
      valor: 600,
      forma_pagamento: 'pix',
      status: 'RECEIVED',
      data_pagamento: dataAtras(70),
      lembrete_enviado_em: null,
      invoice_url: null,
      created_at: isoAtras(72),
    },
    {
      id: 'pag-2',
      os_id: 'os-2',
      asaas_payment_id: 'demo_pay_2',
      valor: 600,
      forma_pagamento: 'cartao_credito',
      status: 'PENDING',
      data_pagamento: null,
      lembrete_enviado_em: null,
      invoice_url: 'https://sandbox.asaas.com/i/demo_pay_2',
      created_at: isoAtras(5),
    },
    {
      id: 'pag-3',
      os_id: 'os-3',
      asaas_payment_id: 'demo_pay_3',
      valor: 550,
      forma_pagamento: 'boleto',
      status: 'OVERDUE',
      data_pagamento: null,
      lembrete_enviado_em: isoAtras(2),
      invoice_url: 'https://sandbox.asaas.com/i/demo_pay_3',
      created_at: isoAtras(9),
    },
  ],

  contas_pagar: [
    {
      id: 'cp-1',
      descricao: 'Aluguel da loja - mês vigente',
      categoria: 'aluguel',
      fornecedor_id: null,
      valor: 3500,
      data_vencimento: dataNoFuturo(4),
      data_pagamento: null,
      status: 'pendente',
      created_at: isoAtras(10),
    },
    {
      id: 'cp-2',
      descricao: 'Fatura laboratório de lentes',
      categoria: 'laboratorio',
      fornecedor_id: 'forn-1',
      valor: 1200,
      data_vencimento: dataAtras(3),
      data_pagamento: null,
      status: 'pendente',
      created_at: isoAtras(15),
    },
    {
      id: 'cp-3',
      descricao: 'Fornecedor de armações - pedido #55',
      categoria: 'fornecedor',
      fornecedor_id: 'forn-2',
      valor: 2100,
      data_vencimento: dataAtras(20),
      data_pagamento: dataAtras(20),
      status: 'pago',
      created_at: isoAtras(35),
    },
    {
      id: 'cp-4',
      descricao: 'Salário funcionários',
      categoria: 'funcionarios',
      fornecedor_id: null,
      valor: 6800,
      data_vencimento: dataNoFuturo(10),
      data_pagamento: null,
      status: 'pendente',
      created_at: isoAtras(5),
    },
  ],

  estoque_movimentos: [
    { id: 'mov-1', produto_id: 'prod-1', tipo: 'entrada', quantidade: 15, motivo: 'correcao_inventario', funcionario_id: 'func-admin', data: isoAtras(500) },
    { id: 'mov-2', produto_id: 'prod-1', tipo: 'saida', quantidade: 3, motivo: 'outro', funcionario_id: 'func-vend-1', data: isoAtras(60) },
    { id: 'mov-3', produto_id: 'prod-2', tipo: 'entrada', quantidade: 6, motivo: 'correcao_inventario', funcionario_id: 'func-admin', data: isoAtras(480) },
    { id: 'mov-4', produto_id: 'prod-2', tipo: 'saida', quantidade: 4, motivo: 'outro', funcionario_id: 'func-vend-1', data: isoAtras(40) },
    { id: 'mov-5', produto_id: 'prod-2', tipo: 'saida', quantidade: 1, motivo: 'quebra', funcionario_id: 'func-vend-1', data: isoAtras(10) },
  ],

  comissoes: [
    {
      id: 'com-1',
      funcionario_id: 'func-vend-1',
      os_id: 'os-1',
      percentual_ou_valor: 5,
      tipo: 'percentual',
      valor_calculado: 30,
      status: 'pago',
      created_at: isoAtras(65),
    },
    {
      id: 'com-2',
      funcionario_id: 'func-vend-1',
      os_id: 'os-3',
      percentual_ou_valor: 5,
      tipo: 'percentual',
      valor_calculado: 27.5,
      status: 'pendente',
      created_at: isoAtras(8),
    },
  ],

  regras_comissao: [
    {
      funcionario_id: 'func-vend-1',
      tipo: 'percentual_fixo',
      percentual_fixo: 5,
      regras_categoria: {},
      valor_fixo: null,
      updated_at: isoAtras(300),
    },
  ],

  campanhas_marketing: [
    {
      id: 'camp-1',
      nome: 'Volta às aulas - troca de óculos',
      canal: 'whatsapp',
      mensagem: 'Olá {nome_cliente}! Aproveite a campanha de volta às aulas e garanta seu novo óculos com condição especial.',
      segmento: 'inativos',
      inatividade_meses: 6,
      clientes_selecionados: null,
      data_envio: isoAtras(15),
      status: 'enviada',
      destinatarios_total: 42,
      destinatarios_sucesso: 39,
      destinatarios_falha: 3,
      taxa_abertura: null,
      created_at: isoAtras(16),
    },
    {
      id: 'camp-2',
      nome: 'Lembrete de revisão anual',
      canal: 'email',
      mensagem: 'Olá {nome_cliente}, já faz um tempo desde sua última consulta ({ultima_compra}). Que tal agendar uma revisão?',
      segmento: 'receita_vencida',
      inatividade_meses: null,
      clientes_selecionados: null,
      data_envio: null,
      status: 'rascunho',
      destinatarios_total: null,
      destinatarios_sucesso: null,
      destinatarios_falha: null,
      taxa_abertura: null,
      created_at: isoAtras(2),
    },
  ],

  configuracoes_loja: [
    {
      id: 'config-1',
      nome: 'Ótica Monte Sinai',
      cnpj: '11.222.333/0001-44',
      endereco: 'Rua das Óticas, 123 - Centro - São Paulo/SP',
      telefone: '(11) 3222-1000',
      email: 'contato@oticamontesinai.com',
      logo_url: null,
      formas_pagamento_aceitas: ['pix', 'cartao_credito', 'cartao_debito'],
      mensagens_automaticas: {
        os_pronta: { ativo: true, canal: 'whatsapp', template: 'Olá {nome_cliente}, seu pedido #{numero_os} está pronto para retirada!' },
        parcela_vencendo: { ativo: true, canal: 'whatsapp', template: 'Olá {nome_cliente}, sua parcela de {valor} vence em {data_vencimento}.' },
        parcela_vencida: { ativo: false, canal: 'email', template: 'Olá {nome_cliente}, identificamos uma parcela em atraso de {valor}.' },
        lembrete_troca: { ativo: false, canal: 'email', template: 'Olá {nome_cliente}, já faz um tempo desde sua última troca de óculos!' },
      },
      desconto_limite_percentual: 10,
      parcelamento_maximo: 6,
      estoque_minimo_padrao: 3,
      comissao_padrao: { tipo: 'percentual_fixo', percentual_fixo: 5 },
      updated_at: isoAtras(100),
    },
  ],

  logs_auditoria: [
    {
      id: 'log-1',
      funcionario_id: 'func-vend-1',
      acao: 'aplicar_desconto',
      tabela_afetada: 'ordens_servico',
      registro_id: 'os-3',
      detalhes: { valor: 20, percentual: 3.4, motivo: 'Cliente indicou outros clientes' },
      created_at: isoAtras(10),
    },
    {
      id: 'log-2',
      funcionario_id: 'func-vend-1',
      acao: 'alterar_status_os',
      tabela_afetada: 'ordens_servico',
      registro_id: 'os-2',
      detalhes: { de: 'em_producao', para: 'pronto' },
      created_at: isoAtras(3),
    },
    {
      id: 'log-3',
      funcionario_id: 'func-fin-1',
      acao: 'editar_financeiro',
      tabela_afetada: 'contas_pagar',
      registro_id: 'cp-3',
      detalhes: { descricao: 'Fornecedor de armações - pedido #55', valor: 2100, acao_especifica: 'marcar_como_pago' },
      created_at: isoAtras(20),
    },
  ],
}

export function proximoNumeroOS() {
  const maior = db.ordens_servico.reduce((max, os) => Math.max(max, os.numero), 1000)
  return maior + 1
}
